### ISSUE TITLE
No config file

### ISSUE THREAD

**Issue by Tidgem** [denoflionsx/HuntControl#1]
Hey man, I only play solo so this mod is a life saver. (24 hours I mean really?).

2 things, it's not generating a config file so I can't speed up the mission timers sadly.

Secondly could you make it also affect refining, growing and dominating servants/converting them?
Essentially could everything on a timer work offline? Except the blood heart... and dying and stuff haha.

If that's a lot to ask (I think it is), then just enabling the config would be a huge help thank you. if it's an error on my end could you attach a sample config file so I can write my own?

Cheers and thank you for the awesome mod.

**Comment by denoflionsx** [comment]
You're looking in the wrong place for the config file. This is a server side mod. Single player just boots a local server which has its own BepInEx folder when using ServerLaunchFix. You need to go into the BepInEx_Server/config folder.

That is currently a lot to ask. This game isn't documented so anything I want to change I have to reverse engineer myself or hope one of the few other modders know anything about it. I only just figured out how injury timers work yesterday. My mod may eventually cover more timers as we understand how the game's systems work.

**Comment by Tidgem** [comment]
Hi I didn't have that server fix mod installed so it wasn't even generating. All good now though thank you for your pointers :)

**Comment by Tidgem** [comment]
Hey so little update.

Is there any way to get this mod to work on LAN mode? And it's not generating config any stuff to do with injuries/timers. Thank you for your replies.

**Comment by denoflionsx** [comment]
The mod works fine on LAN mode. I just tested it and the config generated as expected.

Make sure you're using an up to date version of the mod. Injury timer options weren't added until 1.1

**Comment by Tidgem** [comment]
![image](https://user-images.githubusercontent.com/86493383/177057292-7033610d-ebc2-457a-848c-2d3e7b12dd95.png)
What is the limit that I can set it to then? I have it set to 24 so that 24 hour hunts only take an hour as It makes sense for how I play it. But it still says 23 hours and such...

Is there something I'm doing wrong with the config?

![image](https://user-images.githubusercontent.com/86493383/177057319-3265708d-cbc5-43ed-a9e0-7b2e71d97e64.png)

**Comment by denoflionsx** [comment]
The multiplier doesn't instantly reduce the time.

Every 60 seconds it removes an extra amount of time from the timer based on the following math: (60 * multiplier) - 60. If you sit in the throne and just watch the timer you can see it suddenly drop time when the mod does a processing tick.

**Comment by Tidgem** [comment]
Ahhh okay. Yep it works thanks man! I wish  you all the best with modding, you're doing a good job and helping loners like me who can't play on servers :)
